version: '3.9'

services:

  postgres:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  webserver:
    build: .
    container_name: webservice
    ports:
      - "8076:8076"

  app:
    build: https://github.com/egorioo/UniversityManagmentSystemSpringMVC.git
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - webserver
    environment:
      URL: http://host.docker.internal:8076/groups